import "./style.css";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Home - Paysa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
